ACCESSTOKEN: 

ASCP_EGA_HOST: 
ASCP_EGA_USER: 
ASPERA_SCP_PASS: 
EGA_DCK_KEY: 

PYTHONPATH: /home/ubuntu/icgconnect

STORAGEURL_COLLAB: https://storage.cancercollaboratory.org:443

METADATAURL_COLLAB: https://song.cancercollaboratory.org

STORAGEURL_AWS: https://virginia.cloud.icgc.org
METADATAURL_AWS: https://virginia.song.icgc.org

SONG_SERVER_COLLAB: https://song.cancercollaboratory.org
SONG_SERVER_AWS: https://virginia.song.icgc.org

AWS_ACCESS_KEY_ID: 
AWS_SECRET_ACCESS_KEY: 
COLLAB_ACCESS_KEY_ID: 
COLLAB_SECRET_ACCESS_KEY: 

JT_USER: <username>
JT_SERVER: http://10.0.0.14:8001
