---
- hosts: ega_transfer
  gather_facts: yes
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
  tasks:
    - name: apt-get update
      become: yes
      apt:
        update_cache: yes
    - name: Install pip3
      apt: name=python3-pip=8.1.1-2ubuntu0.4 state=present
    - name: Install pip
      apt: name=python-pip=8.1.1-2ubuntu0.4 state=present
    - name: Install JTracker
      command: pip3 install jtracker==0.2.0a28
    - name: Install samtools
      apt: name=samtools state=latest
    - name: Install Song payload library
      command: pip3 install git+https://github.com/baminou/overture-song-payload.git@0.0.1#egg=overture_song_payload
    - name: Install jsonschema
      command: pip3 install jsonschema==2.6.0
    - name: Add Docker GPG key
      become: true
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    - name: Install list of packages
      apt:
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
        #state: present
        #update_cache: yes
    - name: Change user rights for docker
      become: true
      command: usermod -aG docker ubuntu


    - name: Install cwltool
      command: pip install cwltool==1.0.20180116213856
    - name: Install R
      apt: name=r-base-core state=latest

    - name: Install add-apt-repostory
      apt: name=software-properties-common state=latest
    - name: Add Oracle Java Repository
      apt_repository: repo='ppa:webupd8team/java'
    - name: Select button oracle licence
      command: bash -c "echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections"

    - name: Press ok oracle licence
      command: bash -c "echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections"

    - name: Install Oracle Java 8
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default

    - name: Unarchive Score client
      unarchive:
        src: https://artifacts.oicr.on.ca/artifactory/dcc-release/bio/overture/score-client/1.5.0/score-client-1.5.0-dist.tar.gz
        dest: /home/ubuntu
        remote_src: yes

    - name: Add Score to path
      lineinfile: dest=/home/ubuntu/.bashrc line='export PATH=$PATH:/home/ubuntu/score-client-1.5.0/bin'

    - name: Copy .jtconfig
      copy:
        src: "{{jtconfig}}"
        dest: /home/ubuntu/.jtconfig

    - name: Copy .bashrc
      copy:
        src: "{{bashrc}}"
        dest: /home/ubuntu/.bashrc
